
SLACK_WORKSPACE="T02B8EC7M0S"
SLACK_CHANNEL="C02BM39UNRX"

## Project Repository
BRANCH_NAME="prod"

## Project_Name
PROJECT_NAME="github-action"
# PROJECT_NAME=""
# ENV_NAME=""


# BUCKET_HOSTING = ""
# PIPELINE_NAME = ""
